apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.>
      requests:
        - url: https://webexapis.com/v1/webhooks/incoming/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svNjU4YTgyYmMtOTBhMC00YTk0LTgzM2QtZmE1YjRjZDU0MzI3
          payload: >-
            {"markdown":"Evaluation {{.time}} {{.data.project}} {{.data.service}} {{.data.stage}} {{.source}} {{.id}} {{.type}}"}
          headers:
            - key: Content-Type
              value: application/json
          method: POST
      subscriptionID: 47801132-eb2c-4548-9b67-03a10451261a
      sendFinished: false
      sendStarted: false
